name: Publish Package to npmjs
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get release version from tag
        run: |
          VERSION=${GITHUB_REF_NAME#v}
          echo Version: $VERSION
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      # this would
      # - name: Ensure tag matches package.json version
      #   run: npm version ${VERSION}
      - run: npm publish --provenance --access public --dry-run
        env:
          NODE_AUTH_TOKEN: ${{ secrets.KEENMATE_NPM_TOKEN}}
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          body: |
            Release: ${VERSION}
          draft: true
